#!/bin/sh

# Args:
#  $1 some shell code
#  $2...$N Arguments that will be prepended to the argument list
#  $N+1 or - File or stream containing the arguments to pass to $1
#
# Example:
#  pwd | apply ls

. "$(cd $(dirname "$0") && pwd)/.clojure.sh"

if [ ! -t 0 ]
then
  IN=-
  A="$@"
else
  IN="${@: -1}"
  A=$(but_last_arg "$@")
fi

cat $IN | xargs $A;
