#!/bin/sh

. "$(cd $(dirname "$0") && pwd)/.clojure.sh"

if [ ! -t 0 ]
then
  declare -r IN=-
  declare -a A="$@"
else
  declare -r IN="$1"
  declare -a A="${@:2}"
fi

to_cat $IN

for var in $A
do
  echo "$var"
done
