#!/bin/sh

. "$(cd $(dirname "$0") && pwd)/.clojure.sh"

if [ $# -eq 0 ] && [ ! -t 0 ]
then
  declare -a values=$(cat -)
else
  declare -a values="$@"
fi

while true
do
  for v in $values
  do
    echo $v
  done
done
