#!/bin/sh

. "$(cd $(dirname "$0") && pwd)/.clojure.sh"

to_cat "$2" | while read l; do
  if [ ! -z "$FOUND" ]
  then
    echo $l
  elif ! $SHELL -c "$1" -- $l
  then
    FOUND=1
    echo $l
  fi;
done
