#!/bin/sh

# exits with 0 if any line doesn't match the predicate
#
# Args:
#  $1 test script
#  $2 or - Input file or stream
. "$(cd $(dirname "$0") && pwd)/.clojure.sh"

to_cat "$2" | while read l; do
  $SHELL -c "$1" $l $l
  if [ ! $? -eq 0 ]
  then
    exit 0;
  fi
done

exit 1
