#!/bin/sh

. "$(cd $(dirname "$0") && pwd)/.clojure.sh"


# Arguments
# repeat <v>: infinite stream of <v>
# repeat <n> <v>: stream of <n> <v>s
#
# NOTE: conflicts with the shell builtin 'repeat'

n=-1

case $# in
  1)
    v=$1
    ;;
  2)
    n=$1
    v=$2
    ;;
  *)
    echo "HALP"
    exit -1
    ;;
esac

while [ 0 -ne $n ]
do
  echo $v
  : $(( n -= 1 ))
done
